/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IOCProj63.FactoryBean_Injection.poc;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
